"use client";

import { FormEvent, useEffect, useState } from "react";
import { KeyRound, Loader2, UserPlus, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createUser, listUsers, resetUserPassword, setUserActive } from "@/lib/backend";

type User = { usuario: string; nombre: string; rol: string; activo: boolean; protegido?: boolean };

export function AccessDialog() {
  const [open,setOpen]=useState(false); const [users,setUsers]=useState<User[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{setUsers(await listUsers());}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar los usuarios.");}finally{setLoading(false);}}
  useEffect(()=>{if(open)void load();},[open]);
  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const f=event.currentTarget;const d=Object.fromEntries(new FormData(f).entries());try{await createUser(String(d.usuario),String(d.nombre),String(d.password),String(d.rol));f.reset();await load();}catch(e){setError(e instanceof Error?e.message:"No se pudo crear el usuario.");}finally{setLoading(false);}}
  async function toggle(user:User){setLoading(true);try{await setUserActive(user.usuario,!user.activo);await load();}catch(e){setError(e instanceof Error?e.message:"No se pudo cambiar el acceso.");}finally{setLoading(false);}}
  async function reset(user:User){const password=window.prompt(`Nueva contraseña para ${user.nombre} (mínimo 8 caracteres):`);if(!password)return;setLoading(true);try{await resetUserPassword(user.usuario,password);window.alert("Contraseña actualizada.");}catch(e){setError(e instanceof Error?e.message:"No se pudo cambiar la contraseña.");}finally{setLoading(false);}}
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-white text-[#0d2c3e] hover:bg-slate-100"><Users className="h-4 w-4"/><span className="hidden md:inline">Accesos</span></Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>ADMINISTRAR ACCESOS</DialogTitle></DialogHeader><form onSubmit={add} className="rounded-xl border bg-slate-50 p-4"><div className="mb-3 flex items-center gap-2 font-semibold"><UserPlus className="h-4 w-4"/>NUEVO USUARIO</div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">NOMBRE COMPLETO<Input name="nombre" required className="mt-1 bg-white"/></label><label className="text-sm font-medium">USUARIO<Input name="usuario" required className="mt-1 bg-white"/></label><label className="text-sm font-medium">CONTRASEÑA<Input name="password" type="password" minLength={8} required className="mt-1 bg-white"/></label><label className="text-sm font-medium">ROL<select name="rol" className="mt-1 h-10 w-full rounded-md border bg-white px-3"><option value="OPERADOR">OPERADOR</option><option value="ADMINISTRADOR">ADMINISTRADOR</option></select></label></div><Button disabled={loading} className="mt-3 w-full bg-[#0d2c3e]">AGREGAR USUARIO</Button></form>{error&&<p className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<section><h3 className="mb-2 text-sm font-semibold">USUARIOS REGISTRADOS</h3>{loading&&users.length===0?<Loader2 className="mx-auto h-5 w-5 animate-spin"/>:<div className="space-y-2">{users.map(user=><div key={user.usuario} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-medium">{user.nombre}</p><p className="text-sm text-slate-500">{user.usuario} · {user.rol}{user.protegido?" · CUENTA PRINCIPAL":""}</p></div><div className="flex gap-2"><Button type="button" variant="outline" size="sm" onClick={()=>void reset(user)}><KeyRound className="h-4 w-4"/>Contraseña</Button>{!user.protegido&&<Button type="button" variant={user.activo?"outline":"default"} size="sm" onClick={()=>void toggle(user)}>{user.activo?"Desactivar":"Activar"}</Button>}</div></div>)}</div>}</section></DialogContent></Dialog>;
}
