"use client";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {listSealPeople,saveExternalPerson} from "@/lib/backend";
import {sealPerson,type SealPerson} from "@/lib/seal-people";
import {searchSealPeople,isSecurityPerson} from "@/lib/seal-search";
export function SealParticipants({onChange}:{onChange:(responsable:SealPerson|null,asistentes:SealPerson[])=>void}){
 const [people,setPeople]=useState<SealPerson[]>([]),[officer,setOfficer]=useState<SealPerson|null>(null),[attendees,setAttendees]=useState<SealPerson[]>([]);
 const [officerQuery,setOfficerQuery]=useState(""),[attendeeQuery,setAttendeeQuery]=useState(""),[officerSearching,setOfficerSearching]=useState(false),[manual,setManual]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true);
 const [draft,setDraft]=useState({documento:"",nombre:"",cargo:"",empresa:""});
 useEffect(()=>{let active=true;listSealPeople().then(result=>{if(active){setPeople(result.people);setNotice(result.warning||"");}}).catch(e=>active&&setNotice(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false};},[]);
 function chooseOfficer(person:SealPerson){if(!isSecurityPerson(person))return;if(attendees.some(p=>p.documento===person.documento)){setError("Esta persona ya está incluida como asistente.");return;}setOfficer(person);setOfficerQuery(`${person.documento} · ${person.nombre}`);setOfficerSearching(false);setError("");onChange(person,attendees);}
 function chooseAttendee(person:SealPerson){if(person.documento===officer?.documento||attendees.some(p=>p.documento===person.documento)){setError("Esta persona ya está incluida.");return;}const next=[...attendees,person];setAttendees(next);onChange(officer,next);setAttendeeQuery("");setManual(false);setError("");}
 async function external(){try{setSaving(true);setError("");const person=sealPerson({...draft,origen:"Externo"});if(person.documento===officer?.documento||attendees.some(p=>p.documento===person.documento))throw new Error("Esta persona ya está incluida.");await saveExternalPerson(person);setPeople(current=>[...current.filter(p=>p.documento!==person.documento),person]);setManual(false);setAttendeeQuery(person.documento);setDraft({documento:"",nombre:"",cargo:"",empresa:""});}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.");}finally{setSaving(false);}}
 const officerMatches=searchSealPeople(people.filter(isSecurityPerson),officerQuery),attendeeMatches=searchSealPeople(people,attendeeQuery);
 function results(matches:SealPerson[],choose:(p:SealPerson)=>void){return <div className="max-h-48 overflow-auto rounded-lg border">{matches.map(p=><button key={`${p.origen}-${p.documento}`} type="button" className="block w-full border-b p-2 text-left text-sm hover:bg-slate-50" onClick={()=>choose(p)}>{p.documento} · {p.nombre}<span className="block text-xs text-slate-500">{p.cargo} · {p.empresa}</span></button>)}</div>;}
 return <div className="space-y-4 sm:col-span-2">
 <div className="space-y-1.5"><label htmlFor="seal-officer" className="text-sm font-medium">FUNCIONARIO DE SEGURIDAD DE TURNO</label><Input id="seal-officer" type="search" required value={officerQuery} onChange={e=>{setOfficerQuery(e.target.value);setOfficerSearching(true);setOfficer(null);onChange(null,attendees);setError("");}} autoComplete="off" placeholder="Documento o nombre"/>
 {officerSearching&&officerQuery.trim()&&officerMatches.length>0&&results(officerMatches,chooseOfficer)}
 {officerSearching&&officerQuery.trim()&&!loading&&!officerMatches.length&&<p className="text-xs text-slate-500">No se encontraron coincidencias en el área de Seguridad.</p>}
 {officer&&<p className="text-xs text-slate-500">{officer.cargo} · {officer.empresa}</p>}</div>
 <div className="space-y-1.5"><label htmlFor="seal-attendees" className="text-sm font-medium">ASISTENTES</label><Input id="seal-attendees" type="search" value={attendeeQuery} onChange={e=>{setAttendeeQuery(e.target.value);setManual(false);setError("");}} autoComplete="off" placeholder="Documento o nombre"/>
 {attendeeQuery.trim()&&attendeeMatches.length>0&&results(attendeeMatches,chooseAttendee)}
 {attendeeQuery.trim()&&!loading&&!attendeeMatches.length&&<p className="text-xs text-slate-500">No se encontraron coincidencias.</p>}
 <Button type="button" variant="outline" disabled={loading||saving} onClick={()=>{if(attendeeMatches.length===1){chooseAttendee(attendeeMatches[0]);return;}setManual(false);document.getElementById("seal-attendees")?.focus();setError(attendeeMatches.length>1?"Selecciona el funcionario en los resultados.":"Busca por documento o nombre al funcionario que quieres agregar.");}}>+ AGREGAR ASISTENTE</Button>
 {attendeeQuery.trim()&&!loading&&!attendeeMatches.length&&<Button type="button" variant="outline" disabled={saving} onClick={()=>{const query=attendeeQuery.trim();setDraft({documento:/^[\d.\s-]+$/.test(query)?query.replace(/[.\s-]/g,""):"",nombre:/^[\d.\s-]+$/.test(query)?"":query,cargo:"",empresa:""});setManual(true);setError("");}}>REGISTRAR FUNCIONARIO</Button>}
 {attendees.map(p=><div key={p.documento} className="flex items-center justify-between gap-2 rounded-lg bg-slate-50 p-2 text-sm"><span>{p.documento} · {p.nombre}<span className="block text-xs text-slate-500">{p.cargo} · {p.empresa}</span></span><button type="button" aria-label={`Quitar a ${p.nombre}`} onClick={()=>{const next=attendees.filter(x=>x.documento!==p.documento);setAttendees(next);onChange(officer,next);}}>×</button></div>)}</div>
 {manual&&<div className="grid gap-3 rounded-lg border bg-slate-50 p-3 sm:grid-cols-2">{([['documento','DOCUMENTO'],['nombre','NOMBRE COMPLETO'],['cargo','CARGO'],['empresa','EMPRESA']] as const).map(([key,label])=><label key={key} className="text-sm font-medium">{label}<Input value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<Button type="button" disabled={saving} onClick={()=>void external()} className="sm:col-span-2">{saving?"GUARDANDO…":"GUARDAR FUNCIONARIO"}</Button><p className="text-xs text-slate-500 sm:col-span-2">La persona se guarda solo en Explosivos.</p></div>}
 {loading&&<p className="text-xs text-slate-500">Cargando personal…</p>}{notice&&<p className="text-xs text-amber-800">{notice}</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
 </div>;
}
